name = "threepi_bsp"
description = ""
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "BSD-3-Clause"
website = ""
tags = []

[[depends-on]]
rp2040_hal = "^2.0.1"

#[configuration.values]
#rp2040_hal.Flash_Chip = "w25qxx"

[[depends-on]]
adl_middleware = "~0.2.0"

[[pins]]
rp2040_hal = { url='https://github.com/JeremyGrosser/rp2040_hal.git' }
